### ISSUE TITLE
מובייל - שיתוף באמצעות מייל

### ISSUE THREAD

**Issue by boozyv** [appsGim/CatPouch_December_2017#3]
- היכנס לעמוד הראשי
- בחן את תחתית העמוד - שיתוף באמצעות

תוצאה בפועל:
במובייל לא צריך להופיע שיתוף באמצעות מייל, רק בדסקטופ.

![default](https://user-images.githubusercontent.com/30648580/33424708-4bb14aa2-d5c5-11e7-8d97-a32c4fa39d7f.png)

**Comment by idoshhh** [comment]
Not an issue. 
has been on the psd file of the design.
