### ISSUE TITLE
שדה מייל

### ISSUE THREAD

**Issue by boozyv** [appsGim/CatPouch_December_2017#4]
- היכנס לעמוד הראשי
- הזן בשדה מייל אות בעברית
- בחן תוצאה

תוצאה בפועל:
לאחר הזנת אות בעברית קופצת הודעת שגיאה אך האות הוזנה, ניתן לחזור על הפעולה הזו וכל פעם להזין אות אחת.

**Comment by idoshhh** [comment]
Fixed. Added new validation..
