### ISSUE TITLE
iPhone 5 - תצוגת מסך ראשי

### ISSUE THREAD

**Issue by boozyv** [appsGim/CatPouch_December_2017#5]
***iPhone5***

- היכנס לעמוד הראשי
- בחן את תצוגת המסך

תוצאה בפועל:
כשהמסך נטען בכניסה הוא חורג ולא מותאם לגודל המסך. באמצעות "צביטת" המסך ניתן לתקן את זה.
ראה תמונה

לאחר עלייה:

![img_3122](https://user-images.githubusercontent.com/30648580/33428036-0d4a29f4-d5d0-11e7-9cc0-9873f1a0f334.PNG)

לאחר "צביטה":

![img_3123](https://user-images.githubusercontent.com/30648580/33428048-1a7be19e-d5d0-11e7-9f58-cc9312ced7e7.PNG)

**Comment by idoshhh** [comment]
Fixed.
Added this line to disable zoom pinch:

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
